// blog-post-app/src/components/AuthorSelect.vue
<template>
  <div>
    <select
      id="authorSelect"
      v-model="authorId"
      v-on:change="onAuthorChange($event.target.value)"
      class="form-control"
    >
      <option v-for="author in authorList" :key="author.id" :value="author.id">
        {{ author.name }}
      </option>
    </select>
  </div>
</template>

<script>
import gql from "graphql-tag";
const GET_AUTHORS = gql`
  {
    queryAuthor {
      id
      name
    }
  }
`;
export default {
  props: ["author", "method"],
  data() {
    return {
      authorList: [{ id: "default", name: "Select an Author" }],
      authorId: "Select Author",
    };
  },
  watch: {
    author: {
      handler: function() {
        if (this.author !== undefined) {
          this.authorId = this.author;
        } else {
          this.authorId = this.authorList[0].id;
        }
        this.method(this.authorId);
      },
      immediate: true,
    },
  },
  mounted() {
    this.$apollo
      .query({
        query: GET_AUTHORS,
        fetchPolicy: "network-only",
      })
      .then((data) => {
        this.authorList = data.data.queryAuthor;

        if (this.author !== undefined) {
          this.authorId = this.author;
        } else {
          this.authorId = this.authorList[0].id;
        }
        this.method(this.authorId);
      });
  },
  methods: {
    onAuthorChange: function() {
      this.method(this.authorId);
    },
  },
};
</script>

// blog-post-app/blog-post-react/src/components/AuthorSelect.js
import React, { useState } from "react";

import gql from "graphql-tag";
import { Query } from "react-apollo";

const GET_AUTHORS = gql`
  {
    queryAuthor {
      id
      name
    }
  }
`;

export default function AuthorSelect({ onChange, author }) {
  let authorName = "Select Author"
  if (author !== "") {
    authorName = author
  }
  const [value, setValue] = useState(authorName);

  return (
    <Query query={GET_AUTHORS}>
      {({ loading, error, data }) => {
        if (loading) {
          return <div>Fetching Authors...</div>;
        }
        if (error) {
          return <div>Error: {error}</div>;
        }

        const authorList = [
          { id: "default", name: "Select an Author" },
          ...data.queryAuthor
        ];

        const onSelectboxChange = e => {
          setValue(e.target.value);

          const selectedIndex = e.target.options.selectedIndex;
          const authorId = authorList[selectedIndex].id;
          const authorName = e.target.value;
          onChange(authorName, authorId);
        };

        return (
          <select
            id="authorSelect"
            value={value}
            onChange={onSelectboxChange}
            className="form-control"
          >
            {authorList.map(({ name, id }) => (
              <option value={name} key={id}>
                {name}
              </option>
            ))}
          </select>
        );
      }}
    </Query>
  );
}
