// blog-post-app/src/views/EditPost.vue
<template>
  <div class="container">
    <div class="form-group">
      <label htmlFor="authorSelect">Author:</label>
      <AuthorSelect v-bind:author="authorId" :method="changeAuthor" />
    </div>
    <div class="form-group">
      <label htmlFor="postTitle">Title:</label>
      <input
        id="postTitle"
        class="form-control"
        v-model="title"
        type="text"
        placeholder="Add Title"
      />
    </div>
    <div class="form-group">
      <label htmlFor="postTags">Tags (Press enter to add a tag):</label>
      <vue-tags-input
        v-model="tag"
        :tags="tags"
        @tags-changed="(newTags) => (tags = newTags)"
      />
    </div>
    <div class="form-group">
      <label htmlFor="postText">Content:</label>
      <textarea
        id="postText"
        class="form-control"
        rows="15"
        cols="100"
        v-model="text"
        type="text"
        placeholder="Add your blog post"
      />
    </div>
    <button type="button" class="btn btn-primary" v-on:click="addPost()">
      Publish
    </button>
  </div>
</template>

<script>
import VueTagsInput from "@johmun/vue-tags-input";
import AuthorSelect from "../components/AuthorSelect";
import gql from "graphql-tag";

const POST_MUTATION_TAGS = gql`
  mutation updatePost($postID: ID!, $postRemove: PostPatch!) {
    updatePost(input: { filter: { postID: [$postID] }, remove: $postRemove }) {
      post {
        postID
        title
        text
        tags
        author {
          id
          name
        }
      }
    }
  }
`;

const POST_MUTATION = gql`
  mutation updatePost($postSet: PostPatch!, $postID: ID!) {
    updatePost(input: { filter: { postID: [$postID] }, set: $postSet }) {
      post {
        postID
        title
        text
        tags
        author {
          id
          name
        }
      }
    }
  }
`;

const GET_POST = gql`
  query Post($postID: ID!) {
    getPost(postID: $postID) {
      postID
      title
      text
      tags
      numLikes
      isPublished
      author {
        id
        name
        dob
      }
    }
  }
`;

export default {
  components: {
    VueTagsInput,
    AuthorSelect,
  },
  data() {
    return {
      authorId: "",
      title: "Hello",
      text: "",
      tag: "",
      tags: [],
      removeTags: [],
      postID: "",
    };
  },
  mounted() {
    this.postID = this.$route.query.postID;
    this.$apollo
      .query({
        query: GET_POST,
        variables: {
          postID: this.postID,
        },
        fetchPolicy: "network-only",
      })
      .then((data) => {
        const post = data.data.getPost;
        this.title = post.title;
        this.text = post.text;
        this.tags = post.tags.map((tag) => {
          return { text: tag };
        });
        this.removeTags = post.tags;
        this.authorId = post.author.id;
      });
  },
  methods: {
    changeAuthor: function(authorId) {
      this.authorId = authorId;
    },
    addPost: async function() {
      const tagNames = this.tags.map((tag) => tag.text);

      const postRemove = {
        tags: this.removeTags,
      };

      await this.$apollo
        .mutate({
          mutation: POST_MUTATION_TAGS,
          variables: {
            postID: this.postID,
            postRemove: postRemove,
          },
        })
        .then((data) => {});
      const postSet = {
        title: this.title,
        text: this.text,
        tags: tagNames,
        isPublished: true,
        author: {
          id: this.authorId,
        },
      };

      await this.$apollo
        .mutate({
          mutation: POST_MUTATION,
          variables: {
            postSet: postSet,
            postID: this.postID,
          },
        })
        .then((data) => {
          this.$router.push({
            path: "/view",
            name: "view",
            query: { postID: this.postID },
          });
        });
    },
  },
};
</script>

// blog-post-app/blog-post-react/src/components/EditPost.js
import React, { useState } from "react";
import gql from "graphql-tag";
import queryString from "query-string";
import { useQuery, useMutation } from "@apollo/react-hooks"
import { useHistory } from "react-router-dom";
import TagsInput from "react-tagsinput";
import "react-tagsinput/react-tagsinput.css";
import AuthorSelect from "./AuthorSelect";

const POST_MUTATION_TAGS = gql`
  mutation updatePost($postID: ID!, $postRemove: PostPatch!) {
    updatePost(input: {filter: {postID: [$postID]}, remove: $postRemove}) {
      post {
        postID
        title
        text
        tags
        author {
          id
          name
        }
      }
    }
  }
`;

const POST_MUTATION = gql`
mutation updatePost($postSet: PostPatch!, $postID: ID!) {
  updatePost(input: {filter: {postID: [$postID]}, set: $postSet}) {
    post {
      postID
      title
      text
      tags
      author {
        id
        name
      }
    }
  }
}
`;

const GET_POST = gql`
  query Post($postID: ID!) {
    getPost(postID: $postID) {
      postID
      title
      text
      tags
      numLikes
      isPublished
      author {
        id
        name
        dob
      }
    }
  }
`;

export default function EditPost(props) {
  const [title, setTitle] = useState("");
  const [text, setText] = useState("");
  const [authorId, setAuthorId] = useState("");
  const [tags, setTags] = useState([]);
  const [removeTags, setRemoveTags] = useState([]);

  const history = useHistory();

  const handleChangeAuthor = (authorName, authorId) => setAuthorId(authorId);

  const handleChangeTags = tagsSet => {
    setTags(tagsSet);
  };

  const postSet = {
    title,
    text,
    tags,
    isPublished: true,
    author: {
      id: authorId
    }
  }

  const postRemove = {
    tags: removeTags
  }

  let params = queryString.parse(props.location.search);
  let postID = params.postID;
  const { loading, error, data } = useQuery(GET_POST, { variables: { postID }, fetchPolicy: "network-only" });
  const [removePostTags] = useMutation(POST_MUTATION_TAGS)
  const [updatePost] = useMutation(POST_MUTATION)
  
  if (loading) return "Fetching Posts...";
  if (error) return `Error: ${error}`;
  const post = data.getPost;
  if (title === "") {
    setTitle(post.title);
    setText(post.text);
    setTags(post.tags);
    setRemoveTags(post.tags)
    setAuthorId(post.author.id)
  }
  
  return (
    <div className="container">
      <div className="form-group">
        <label htmlFor="authorSelect">Author:</label>
        <AuthorSelect
          author={post.author.name}
          onChange={handleChangeAuthor}
        />
      </div>
      <div className="form-group">
        <label htmlFor="postTitle">Title:</label>
        <input
          id="postTitle"
          className="form-control"
          value={title}
          onChange={e => setTitle(e.target.value)}
          type="text"
          placeholder="Add Title"
        />
      </div>
      <div className="form-group">
        <label htmlFor="postTags">Tags:</label>
        <TagsInput value={tags} onChange={handleChangeTags} />
      </div>
      <div className="form-group">
        <label htmlFor="postText">Content:</label>
        <textarea
          id="postText"
          className="form-control"
          rows="15"
          cols="100"
          value={text}
          onChange={e => setText(e.target.value)}
          type="text"
          placeholder="Add your blog post"
        />
      </div>
      <button
        type="submit"
        className="btn btn-primary"
        onClick={async e => {
          e.preventDefault();
          await removePostTags({ variables: {postID, postRemove}})
          await updatePost({ variables: { postSet, postID} })
          history.push({
            pathname: '/view',
            search: `?postID=${postID}`
          });
        }}
      >
        Publish
          </button>
    </div>
  );
}
