// blog-post-app/src/components/Post.vue
<template>
  <div>
    <div v-for="post in queryPost" :key="post.postID">
      <div class="card col-12 mb-3">
        <div class="card-body card-pointer" v-on:click="viewPost(post.postID)">
          <h5 class="card-title">Title: {{ post.title }}</h5>
          <h6 class="card-subtitle mb-2 text-muted">
            by {{ post.author.name }}
          </h6>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
// import ViewPost from "../views/ViewPost"
export default {
  props: ["queryPost"],
  methods: {
    viewPost(postID) {
      this.$router.push({
        path: "/view",
        name: "view",
        query: { postID: postID },
      });
    },
  },
};
</script>

// blog-post-app/blog-post-react/src/components/Post.js
import React from "react";
import { useHistory } from "react-router-dom"

export default function Post({ post }) {
  const history = useHistory();
  const viewPost = (postID) => {
    history.push({
      pathname: '/view',
      search: `?postID=${postID}`
    })
  }
  return (
    <div className="card col-12 mb-3">
      <div className="card-body card-pointer" onClick={() => viewPost(post.postID)}>
        <h5 className="card-title">Title: {post.title}</h5>
        <h6 className="card-subtitle mb-2 text-muted">
          by {post.author.name}
        </h6>
      </div>
    </div>
  );
}
