// todo-app/todo-app-vue/src/TodoFooter.vue
<template>
  <footer class="footer" v-show="todoLength">
    <span class="todo-count">
      <strong v-text="remaining"></strong> {{pluralize('item', remaining)}} left
    </span>
    <ul class="filters">
      <li><a href="#/all" :class="{selected: visibility == 'all'}">All</a></li>
      <li><a href="#/active" :class="{selected: visibility == 'active'}">Active</a></li>
      <li><a href="#/completed" :class="{selected: visibility == 'completed'}">Completed</a></li>
    </ul>
    <button class="clear-completed" @click="removeCompleted" v-show="todoLength > remaining">
      Clear completed
    </button>
  </footer>
</template>
<script>
export default {
  name: 'TodoFooter',
  props: [
    'pluralize',
    'removeCompleted',
    'remaining',
    'todoLength',
    'visibility'
  ]
}
</script>

// todo-react-firebase/src/TodoFooter.js
import React from 'react'
import classNames from 'classnames'

import defs from './defs'
import Utils from './Utils'

export default class TodoFooter extends React.Component {
  render() {
    const { completedCount, count, nowShowing, onClearCompleted } = this.props
    const clearButton = completedCount === 0
      ? null
      : (
        <button
          className="clear-completed"
          onClick={onClearCompleted}>
          Clear completed
        </button>
      )
    return (
      <footer className="footer">
        <span className="todo-count">
          <strong>{count}</strong> {Utils.pluralize(count, 'item')} left
        </span>
        <ul className="filters">
          <li>
            <a
              href="#/"
              className={classNames({selected: nowShowing === defs.ALL_TODOS})}>
                All
            </a>
          </li>
          {' '}
          <li>
            <a
              href="#/active"
              className={classNames({selected: nowShowing === defs.ACTIVE_TODOS})}>
                Active
            </a>
          </li>
          {' '}
          <li>
            <a
              href="#/completed"
              className={classNames({selected: nowShowing === defs.COMPLETED_TODOS})}>
                Completed
            </a>
          </li>
        </ul>
        {clearButton}
      </footer>
    )
  }
}
