// blog-post-app/blog-post-react/src/components/CreatePost.js
import React, { useState } from "react";
import gql from "graphql-tag";
import { useMutation } from "@apollo/react-hooks";
import { useHistory } from "react-router-dom";
import TagsInput from 'react-tagsinput'
import 'react-tagsinput/react-tagsinput.css'
import AuthorSelect from "./AuthorSelect";

const POST_MUTATION = gql`
  mutation addPost($post: [AddPostInput!]!) {
    addPost(input: $post) {
      post {
        postID
        title
        text
        author {
          id
          name
        }
      }
    }
  }
`;

export default function AddPost(props) {
  const [title, setTitle] = useState("");
  const [text, setText] = useState("");
  const [authorId, setAuthorId] = useState("");
  const [tags, setTags] = useState([])

  const history = useHistory();

  const handleChangeAuthor = (authorName, authorId) =>
    setAuthorId(authorId);

  const post = [{
    title,
    text,
    tags,
    isPublished: true,
    author: {
      id: authorId
    }
  }];

  const handleChangeTags = (tagsSet) => {
    setTags(tagsSet)
  }

  const [addPost] = useMutation(POST_MUTATION)

  return (
    <div className="container">
      <hr />
      <div className="form-group">
        <label htmlFor="authorSelect">Author:</label>
        <AuthorSelect onChange={handleChangeAuthor} />
      </div>
      <div className="form-group">
        <label htmlFor="postTitle">Title:</label>
        <input
          id="postTitle"
          className="form-control"
          value={title}
          onChange={e => setTitle(e.target.value)}
          type="text"
          placeholder="Add Title"
        />
      </div>
      <div className="form-group">
        <label htmlFor="postTags">Tags (Press enter to add a tag):</label>
        <TagsInput value={tags} onChange={handleChangeTags} />
      </div>
      <div className="form-group">
        <label htmlFor="postText">Content:</label>
        <textarea
          id="postText"
          className="form-control"
          rows="15"
          cols="100"
          value={text}
          onChange={e => setText(e.target.value)}
          type="text"
          placeholder="Add your blog post"
        />
      </div>
          <button
              type="submit"
              className="btn btn-primary"
              onClick={async e => {
                e.preventDefault();
                await addPost({ variables: {post}})
                history.push("/");
              }}
          >
            Publish
          </button>
    </div>
  );
}

// blog-post-app/blog-post-vue/src/views/CreatePost.vue
<template>
  <div class="container">
    <hr />
    <div class="form-group">
      <label htmlFor="authorSelect">Author:</label>
      <AuthorSelect :method="changeAuthor" />
    </div>
    <div class="form-group">
      <label htmlFor="postTitle">Title:</label>
      <input
        id="postTitle"
        class="form-control"
        v-model="title"
        type="text"
        placeholder="Add Title"
      />
    </div>
    <div class="form-group">
      <label htmlFor="postTags">Tags (Press enter to add a tag):</label>
      <vue-tags-input
        v-model="tag"
        :tags="tags"
        @tags-changed="(newTags) => (tags = newTags)"
      />
    </div>
    <div class="form-group">
      <label htmlFor="postText">Content:</label>
      <textarea
        id="postText"
        class="form-control"
        rows="15"
        cols="100"
        v-model="text"
        type="text"
        placeholder="Add your blog post"
      />
    </div>
    <button type="button" class="btn btn-primary" v-on:click="addPost()">
      Publish
    </button>
  </div>
</template>

<script>
import VueTagsInput from "@johmun/vue-tags-input";
import AuthorSelect from "../components/AuthorSelect";
import gql from "graphql-tag";

const POST_MUTATION = gql`
  mutation addPost($post: [AddPostInput!]!) {
    addPost(input: $post) {
      post {
        postID
        title
        text
        author {
          id
          name
        }
      }
    }
  }
`;

export default {
  components: {
    VueTagsInput,
    AuthorSelect,
  },
  data() {
    return {
      authorId: "",
      title: "Hello",
      text: "",
      tag: "",
      tags: [],
    };
  },
  methods: {
    changeAuthor: function(authorId) {
      this.authorId = authorId;
    },
    addPost: function() {
      const tagNames = this.tags.map((tag) => tag.text);

      const post = [
        {
          title: this.title,
          text: this.text,
          tags: tagNames,
          isPublished: true,
          author: {
            id: this.authorId,
          },
        },
      ];

      this.$apollo
        .mutate({
          mutation: POST_MUTATION,
          variables: {
            post: post,
          },
        })
        .then(() => {
          this.$router.push({
            path: "/",
            name: "posts",
          });
        });
    },
  },
};
</script>
